### ISSUE TITLE
Themes > Possible bug in water_level fetch code

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#284]
Got the following referring to JSPN.parse line in app.js

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/losullivan/Documents/repos/bcd-dd-v2.1/app.js:269:31
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by LiamOSullivan** [comment]
Suspect this is not failing gracefully e.g. on node process exit file is still being written to when closed

**Comment by LiamOSullivan** [comment]
This file is still causing problems on staging branch on process start:

[Error: ENOENT: no such file or directory, open './public/data/Environment/waterlevel.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './public/data/Environment/waterlevel.json'
}
